databases:
  - name: smart-crop-db
    databaseName: smart_crop_db
    user: smart_crop_user
    region: oregon

services:
  - type: web
    name: smart-crop-advisory
    runtime: python
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn smart_crop.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smart-crop-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 4
