# Generated by Django 4.2.11 on 2025-09-12 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemHealthCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component",
                    models.CharField(help_text="System component name", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "✅ Healthy"),
                            ("warning", "⚠️ Warning"),
                            ("critical", "❌ Critical"),
                            ("unknown", "❓ Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Status message or error details"
                    ),
                ),
                (
                    "response_time",
                    models.FloatField(
                        blank=True, help_text="Response time in seconds", null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "System Health Check",
                "verbose_name_plural": "System Health Checks",
                "db_table": "system_health_checks",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="APIUsageStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(help_text="API endpoint", max_length=200),
                ),
                ("method", models.CharField(help_text="HTTP method", max_length=10)),
                (
                    "ip_address",
                    models.GenericIPAddressField(help_text="Client IP address"),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User agent string"),
                ),
                (
                    "response_status",
                    models.IntegerField(help_text="HTTP response status code"),
                ),
                (
                    "response_time",
                    models.FloatField(help_text="Response time in seconds"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Usage Stat",
                "verbose_name_plural": "API Usage Stats",
                "db_table": "api_usage_stats",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["endpoint", "timestamp"],
                        name="api_usage_s_endpoin_901f42_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="api_usage_s_user_id_bec166_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="api_usage_s_timesta_6486ec_idx"
                    ),
                ],
            },
        ),
    ]
