# Generated by Django 4.2.11 on 2025-09-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserManagement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number in international format",
                max_length=17,
                null=True,
                unique=True,
            ),
        ),
    ]
