# Generated by Django 4.2.11 on 2025-09-11 21:28

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Commodity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cereals", "Cereals"),
                            ("pulses", "Pulses"),
                            ("vegetables", "Vegetables"),
                            ("fruits", "Fruits"),
                            ("spices", "Spices"),
                            ("oilseeds", "Oilseeds"),
                            ("cash_crops", "Cash Crops"),
                            ("others", "Others"),
                        ],
                        max_length=30,
                    ),
                ),
                ("variety", models.CharField(blank=True, max_length=50)),
                ("grade", models.CharField(blank=True, max_length=20)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "Kilogram"),
                            ("quintal", "Quintal"),
                            ("ton", "Ton"),
                            ("dozen", "Dozen"),
                            ("bunch", "Bunch"),
                        ],
                        default="kg",
                        max_length=10,
                    ),
                ),
                ("seasonal", models.BooleanField(default=False)),
                ("harvest_season", models.CharField(blank=True, max_length=50)),
                ("shelf_life_days", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Commodities",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="FarmerTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("sell", "Sell"), ("buy", "Buy")], max_length=10
                    ),
                ),
                (
                    "quantity",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("transaction_date", models.DateField()),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("partial", "Partial"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("location", models.CharField(max_length=200)),
                ("district", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "latitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MinValueValidator(90),
                        ]
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MinValueValidator(180),
                        ]
                    ),
                ),
                (
                    "market_type",
                    models.CharField(
                        choices=[
                            ("wholesale", "Wholesale"),
                            ("retail", "Retail"),
                            ("apmc", "APMC"),
                            ("private", "Private"),
                            ("online", "Online"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("contact_number", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("opening_time", models.TimeField(blank=True, null=True)),
                ("closing_time", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PricePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prediction_date", models.DateField()),
                (
                    "predicted_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MinValueValidator(1),
                        ]
                    ),
                ),
                (
                    "price_range_min",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "price_range_max",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("model_version", models.CharField(max_length=20)),
                (
                    "factors",
                    models.JSONField(
                        default=dict, help_text="Factors influencing the prediction"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="MarketAnalysis.commodity",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="MarketAnalysis.market",
                    ),
                ),
            ],
            options={
                "ordering": ["-prediction_date", "commodity"],
            },
        ),
        migrations.CreateModel(
            name="MarketTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "trend_type",
                    models.CharField(
                        choices=[
                            ("bullish", "Bullish"),
                            ("bearish", "Bearish"),
                            ("sideways", "Sideways"),
                            ("volatile", "Volatile"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price_change_percent", models.FloatField()),
                ("volume_change_percent", models.FloatField(blank=True, null=True)),
                ("average_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "volatility_index",
                    models.FloatField(help_text="Price volatility index (0-100)"),
                ),
                ("key_factors", models.JSONField(default=list)),
                ("analysis_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trends",
                        to="MarketAnalysis.commodity",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trends",
                        to="MarketAnalysis.market",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_end", "commodity"],
            },
        ),
        migrations.CreateModel(
            name="MarketPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "min_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "modal_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "arrivals",
                    models.FloatField(
                        blank=True, help_text="Arrivals in tons", null=True
                    ),
                ),
                (
                    "price_trend",
                    models.CharField(
                        choices=[
                            ("up", "Rising"),
                            ("down", "Falling"),
                            ("stable", "Stable"),
                        ],
                        default="stable",
                        max_length=10,
                    ),
                ),
                ("source", models.CharField(default="manual", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="MarketAnalysis.commodity",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="MarketAnalysis.market",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "market", "commodity"],
            },
        ),
        migrations.CreateModel(
            name="MarketAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("price_above", "Price Above"),
                            ("price_below", "Price Below"),
                            ("price_change", "Price Change %"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "threshold_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                ("trigger_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MarketAnalysis.commodity",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MarketAnalysis.market",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="market",
            index=models.Index(
                fields=["state", "district"], name="MarketAnaly_state_5ef139_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="market",
            index=models.Index(
                fields=["latitude", "longitude"], name="MarketAnaly_latitud_5d2049_idx"
            ),
        ),
        migrations.AddField(
            model_name="farmertransaction",
            name="commodity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="MarketAnalysis.commodity",
            ),
        ),
        migrations.AddField(
            model_name="farmertransaction",
            name="market",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="MarketAnalysis.market"
            ),
        ),
        migrations.AddField(
            model_name="farmertransaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="priceprediction",
            index=models.Index(
                fields=["commodity", "market", "-prediction_date"],
                name="MarketAnaly_commodi_55d917_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="markettrend",
            index=models.Index(
                fields=["commodity", "-period_end"],
                name="MarketAnaly_commodi_35101c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marketprice",
            index=models.Index(
                fields=["market", "commodity", "-date"],
                name="MarketAnaly_market__8135ed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marketprice",
            index=models.Index(fields=["date"], name="MarketAnaly_date_eb40cd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="marketprice",
            unique_together={("market", "commodity", "date")},
        ),
        migrations.AddIndex(
            model_name="marketalert",
            index=models.Index(
                fields=["user", "is_active"], name="MarketAnaly_user_id_021264_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farmertransaction",
            index=models.Index(
                fields=["user", "-transaction_date"],
                name="MarketAnaly_user_id_4823e5_idx",
            ),
        ),
    ]
