# Generated by Django 4.2.11 on 2025-09-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advisory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisoryalert',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='When the alert was marked as read', null=True),
        ),
        migrations.AddField(
            model_name='advisoryalert',
            name='resolution_note',
            field=models.TextField(blank=True, help_text='Note about how the alert was resolved'),
        ),
    ]
